spring:
  application:
    name: spring-boot-projects-mvc-thymeleaf
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
  thymeleaf:
    enabled: true